apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - host: localhost.prd
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-prd
          servicePort: 80        
  - host: localhost.stg
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-stg
          servicePort: 80        

