apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-green
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
        name: {{ .Chart.Name }}
        slot: green
  template:
    metadata:
      namespace: default
      labels:
        name: {{ .Chart.Name }}
        slot: green
    spec:
      containers:
      - name: {{ .Chart.Name }}-green
        image: my-service:{{ .Values.green.version }}
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /weatherforecast/slot
            port: 80
          periodSeconds: 15
          timeoutSeconds: 30
        volumeMounts:
        - name: appsettings
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: appsettings
        configMap:
           name: {{ .Chart.Name }}-green
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      # maxUnavailable: 1
